services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "5001:80"
  parking-service:
    build:
      context: .
      dockerfile: parking-service/Dockerfile
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    stdin_open: true
    tty: true